name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Spring Boot JAR
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload JAR and Properties File to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            target/*.jar
            external.properties
          target: "/home/ubuntu/apps/backend"

      - name: Run JAR on EC2 (Kill old, Start new)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Checking for existing process on port 8080..."
            PID=$(sudo lsof -t -i:8080)
            if [ -n "$PID" ]; then
              echo "Killing process $PID on port 8080"
              sudo kill $PID
            fi

            echo "Starting new JAR in background..."
            cd /home/ubuntu/apps/backend
            nohup java -jar *.jar --spring.config.import=optional:file:external.properties > backend.log 2>&1 &
            disown
