- name: Run JAR on EC2
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      echo "Switching to backend target directory..."
      cd /home/ubuntu/apps/backend/target

      echo "Copying .env file..."
      cp ~/.env .env

      echo "Checking for existing process on port 8080..."
      PID=$(sudo lsof -t -i:8080)
      if [ -n "$PID" ]; then
        echo "Killing process $PID"
        sudo kill $PID
      else
        echo "No process running on port 8080"
      fi

      echo "Running the JAR in background..."
      nohup java -jar LostnFound-Docker.jar > backend.log 2>&1 &

      echo "Disowning the process..."
      disown

      echo "Done!"
